CREATE TABLE soy2_user (
	id integer primary key AUTOINCREMENT, 
	name VARCHAR,
	age UNSIGNED INTEGER NOT NULL DEFAULT 0,
	create_date UNSIGNED INTEGER NOT NULL DEFAULT 0,
	update_date UNSIGNED INTEGER NOT NULL DEFAULT 0
);