CREATE TABLE soy2_sample (
	id integer primary key AUTOINCREMENT, 
	text TEXT,
	is_open UNSIGNED INTEGER NOT NULL DEFAULT 0,
	create_date UNSIGNED INTEGER NOT NULL DEFAULT 0,
	update_date UNSIGNED INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE soy2_relation (
	sample_id UNSIGNED INTEGER NOT NULL UNIQUE,
	text TEXT
);